server {
    listen 80;
    server_name localhost;
    root /var/www/html/backend/public;

    error_log  /var/log/nginx/error.log;
    access_log /var/log/nginx/access.log;

    # Backend API and Symfony entry point
    location ~ ^/(api|index\.php)(/|$) {
        fastcgi_pass php:9000;
        fastcgi_split_path_info ^(.+\.php)(/.*)$;
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $realpath_root$fastcgi_script_name;
        fastcgi_param DOCUMENT_ROOT $realpath_root;
        
        # If it's the index.php, don't let it be accessed directly if it's not /api
        internal;
    }

    # Proxy to React Dev Server (Vite)
    location / {
        proxy_pass http://frontend:5173;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
    }

    location ~ \.php$ {
        return 404;
    }
}
